version: "3.8"

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: 'pgadmin'
    restart: always
    depends_on:
      - postgres
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: gtormo@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password